name: Auto-Merge PRs

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Attempt to merge the pull request
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                merge_method: 'squash'  # Use 'merge' for regular merge, 'squash' for squash merge
              });
              console.log("Pull request merged!");
            } catch (error) {
              console.error("Error merging pull request:", error.message);
            }

      - name: Add 'hacktoberfest-accepted' label
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['hacktoberfest-accepted']
            });
            console.log("Added 'hacktoberfest-accepted' label.");

      - name: Comment on the pull request
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "PR has been automatically merged and labeled as `hacktoberfest-accepted`. Thank you for your contribution!"
            });
            console.log("Commented on the pull request.");
