name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""                    
          MERGE_REMOVE_LABELS: ""                 # No labels to remove after merge
          MERGE_METHOD: "squash"                  # Continue using squash method for merging
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"                    # If PRs from forks should be merged, set this to "true"
          MERGE_RETRIES: "6"                      # Retry merge 6 times if it fails
          MERGE_RETRY_SLEEP: "10000"              # Wait 10 seconds between retries
          MERGE_REQUIRED_APPROVALS: "0"           # No approvals required
          UPDATE_LABELS: ""                       # No update labels needed
          UPDATE_METHOD: "rebase"                 # PRs will be updated via rebase if needed
          PULL_REQUEST: ""                        # Apply to all open pull requests
          MAX_PR_COUNT: "1000"      
