name: Automerge PRs

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Automerge action
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"   # GitHub token is automatically detected
          MERGE_LABELS: ""                              # No labels are required for merge
          MERGE_REMOVE_LABELS: ""                       # No labels are removed after merge
          MERGE_METHOD: "squash"                        # Squash merge method
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "true"                          # Set to "false" to avoid merging forks
          MERGE_RETRIES: "6"                            # Retry merge up to 6 times if needed
          MERGE_RETRY_SLEEP: "10000"                    # Wait 10 seconds between retries
          MERGE_REQUIRED_APPROVALS: "0"                 # No approvals required
          UPDATE_LABELS: ""                             # No specific labels for update
          UPDATE_METHOD: "rebase"                       # Rebases when needed
          PULL_REQUEST: ""                              # No specific PR, applies to all PRs
          MAX_PR_COUNT: "1000"                          # Merges up to 1000 PRs
